### Module 10 Discussion (Untidy Data Sets)

In [59]:
from urllib.request import urlopen
import json 
from pandas.io.json import json_normalize
import pandas as pd
import requests

snap_data = json.loads(requests.get('https://raw.githubusercontent.com/mbjamil92/DAV-5400/main/location_history.json').text)

snap_df = pd.DataFrame.from_dict(df, orient='index').T

In [60]:
snap_df

,Frequent Locations,Latest Location,Home & Work,Daily Top Locations,Top Locations Per Six-Day Period,Location History,Businesses and public places you may have visited,Areas you may have visited in the last two years
0,"{'City': 'east setauket', 'Country': 'usa', 'R...","{'City': 'east setauket', 'Country': 'usa', 'R...",Home,[{'Date: 2021-03-20 UTC': 'lat 40.907 ± 73.37 ...,[{'Date: 2021-02-26 UTC': 'lat 40.908 ± 73.37 ...,"{'Time': '2020/09/26 01:18:36 UTC', 'Latitude,...","{'Date': '2020-11-12', 'Name': 'Checkers & Ral...","{'Time': '2021/01/15 03:26:29 UTC', 'City': 'i..."
1,"{'City': 'east setauket', 'Country': 'usa', 'R...",None,Work,[{'Date: 2021-03-22 UTC': 'lat 40.859 ± 36.71 ...,[{'Date: 2021-03-04 UTC': 'lat 40.908 ± 73.37 ...,"{'Time': '2020/09/26 01:18:40 UTC', 'Latitude,...","{'Date': '2020-08-13', 'Name': 'Panera Bread (...","{'Time': '2020/03/05 20:45:35 UTC', 'City': 'p..."
2,None,None,None,None,[{'Date: 2021-03-10 UTC': 'lat 40.879 ± 73.41 ...,"{'Time': '2020/09/26 01:18:42 UTC', 'Latitude,...","{'Date': '2021-03-15', 'Name': 'Best Buy'}","{'Time': '2020/08/30 20:15:27 UTC', 'City': 's..."
3,None,None,None,None,[{'Date: 2021-03-16 UTC': 'lat 40.908 ± 73.37 ...,"{'Time': '2020/09/26 01:18:43 UTC', 'Latitude,...","{'Date': '2020-11-29', 'Name': 'PINK (US)'}","{'Time': '2020/09/20 19:39:27 UTC', 'City': 's..."
4,None,None,None,None,[{'Date: 2021-03-22 UTC': 'lat 40.859 ± 18.36 ...,"{'Time': '2020/09/26 01:18:57 UTC', 'Latitude,...","{'Date': '2020-08-30', 'Name': 'Walmart'}","{'Time': '2019/06/16 12:48:52 UTC', 'City': 'k..."
...,...,...,...,...,...,...,...,...
2168,None,None,None,None,None,"{'Time': '2021/03/23 02:55:34 UTC', 'Latitude,...",None,None
2169,None,None,None,None,None,"{'Time': '2021/03/23 02:55:34 UTC', 'Latitude,...",None,None
2170,None,None,None,None,None,"{'Time': '2021/03/23 02:55:37 UTC', 'Latitude,...",None,None
2171,None,None,None,None,None,"{'Time': '2021/03/23 02:55:51 UTC', 'Latitude,...",None,None
2172,None,None,None,None,None,"{'Time': '2021/03/23 02:55:51 UTC', 'Latitude,...",None,None